# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d83b822db1e128364cab358c2b831f01fdbcb93bbbaaff234e09c9577f710d4e5f02f87e8fa485939c7996b51f1ef0fe047a82236668ec5aba0e5c59b1cd83

test:
  secret_key_base: f6e87a7e7c32c88be13473e84631ba21ced22bed1a102c0dad55bb407675d1bd037bd5d2b3d2411cdc2b46dad6df13e5830d6dd977b7b1de5eed8b40fe55c522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
